### PR TITLE
Clarify and lighten ruby scaffold

### PR DESCRIPTION
**Pull request by ThomasCollignon**
I've grouped the changes by relevant commits. Feel free to challenge every change.

### CODE REVIEW

**Review by jbruggem — CHANGES_REQUESTED** [review]
Thanks for the PR Thomas ! 

Your help is more than welcome to bring more consistency to this repository. May I ask how you stumbled upon it ?

I'll have to look into it in more details, but I can already comment on the `scripts/test` and `scripts/build` files: they need to be kept. Their purpose I believe is relatively obvious from their name :). They are also expected by the [TCR and BTCR scripts](https://github.com/euranova/code_retreat#tcr).

I realize that we previously merged some changes for the ruby scaffold that are not consistent with what's found for most languages. If you take `julia` or  `elixir` for example, you'll see that there's a script at the root of the folder that encapsulates a command in a docker directly (`julia` and `mix` respectively). This is the recommended approach, instead of having a `./scripts/docker.sh` file.

None of this is not very well documented. I'll push some changes tonight to improve that, as well as the consistency across languages.

Again, thank you very much for your contribution to this repo.

**Comment by ThomasCollignon** [comment]
I've discovered this repo thanks to @Malian, one of the contributors, who uses it for code retreat meetings in our company, Belighted.
Personally I also use it to learn new languages basic scaffolds, and minimal Docker integration.

About the `scripts/test` and `scripts/build`, I've removed them because I didn't read the main README, shame on me.

I see that you've pushed some changes, I'll check them asap and adapt or remove this PR consequently.

**Comment by jbruggem** [comment]
> I've removed them because I didn't read the main README, shame on me.

You're not to blame here, I added those explanations yesterday following your PR. So on the contrary, many thanks for the nudge :).

>  I'll check them asap and adapt or remove this PR consequently.

Thanks ! I haven't changed much in the `ruby` folder, so there still are two competing scripts to run ruby in docker, and that indeed needs to be simplified. So the clarification and lightening is still welcome and necessary :).

**Comment by Malian** [comment]
:wave: @jbruggem

**Comment by ThomasCollignon** [comment]
@jbruggem I have two more questions:

- Why `ENABLE_TTY=${ENABLE_TTY:--t}` instead of just `-t` ? And actually I can't figure out why/how/who would set `ENABLE_TTY`.
- What use do you make of the binstubs generated in the `docker-home` folder ?

**Comment by jbruggem** [comment]
> @jbruggem I have two more questions:
> 
>     * Why `ENABLE_TTY=${ENABLE_TTY:--t}` instead of just `-t` ? And actually I can't figure out why/how/who would set `ENABLE_TTY`.

See `scaffolds/test_all.sh`. The objective is to be able to disable TTY when we're testing all the scripts. The name of the env var is probably not ideal given what it's used for :).

> 
>     * What use do you make of the binstubs generated in the `docker-home` folder ?

I'm not an expert in Ruby, so I have to guess a bit here. I suppose that when I wrote the `ruby-env` script, I wanted:
- to avoid having to build an image
- to cache locally all the files that ruby needs to work correctly, so that running the script is only slow the first time

I suppose that this is why HOME, GEM_HOME and BUNDLE_PATH are set. But let's be clear: I don't know much about ruby at all :). As long as we have something that's easy to maintain, consistent with the rest and easy to use for newbies, it's all good :).

**Comment by ThomasCollignon** [comment]
Sorry for the delay.

I've seen no perf improvement using binstubs, so I've removed it. The goal is to keep only one `docker run` script: it's easier to understand.

**Review by jbruggem — APPROVED** [review]
LGTM !

**Comment by jbruggem** [comment]
Thanks for the contribution @ThomasCollignon !

**Pull request merged**
